### PR TITLE
Increase token per line limit

### PR DESCRIPTION
**Pull request by FoxyDysphoria**

### CODE REVIEW

**Comment by erkyrath** [comment]
Can you explain what this does given the previous (limitLineLength:no) line?

**Comment by FoxyDysphoria** [comment]
Limit line length keeps the grammar from parsing lines over a certain
number of characters in length, whereas max tokens per line sets the max
number of things for it to highlight in any given line.

**Comment by erkyrath** [comment]
Got it. Thanks.

**Comment by erkyrath** [comment]
(And I managed to push the wrong button for this PR, but I added the change anyway.)

**Pull request closed without merging**
